name: Deploy to Dev

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn

      - name: Deploy to Vercel (Dev)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --token=$VERCEL_TOKEN --prod
